/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pointandclickswingproject;
import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;

/**
 *
 * @author Nikhil
 */
public class GameScreen1 extends javax.swing.JPanel {
    Color red = new Color(200, 0, 0);
    Color red1 = new Color(240, 40, 40);
    Color yellow = new Color(215, 170, 53);
    Color yellow1 = new Color(255, 210, 93);
    Color green = new Color(0, 128, 0);
    Color green1 = new Color(40, 168, 40);
    Color blue = new Color(0, 64, 128);
    Color blue1 = new Color(40, 104, 168);
    Color purple = new Color(128, 0, 128);
    Color purple1 = new Color(168, 40, 168);
    
    // x restriction: 20 ~ 500
    // y restriction: 20 ~ 350
    private final int MAX_LOCATIONS = 20;
    private final ArrayList<Point> locations = new ArrayList<>(MAX_LOCATIONS);

    /**
     * Creates new form GameScreen1
     */
    public GameScreen1() {
        initComponents();
        jButton1.setBackground(red);
        jButton2.setBackground(yellow);
        jButton3.setBackground(green);
        jButton4.setBackground(blue);
        jButton5.setBackground(purple);
        initializePossibleLocations();
        randomizeButtonLocations();
//        for(Point l : locations)
//        {
//            System.out.println(l);
//        }
    }
    
    private void initializePossibleLocations()
    {
        locations.removeAll(locations);
        
        // leftmost x coord and topmost y coord
        int x = 50;
        int y = 50;
        
        for(int i = 0; i < MAX_LOCATIONS; i++)
        {
            if(y > 350)
            {
                break;
            }
            else if(x > 500)
            {
                x = 50;
                y += 100;
                
                Point p = new Point(x, y);
                locations.add(p);
                
                x += 100;
                
            }
            else
            {
                Point p = new Point(x, y);
                locations.add(p);
                
                x += 100;
                
            }
        }
    }
    
    private void randomizeButtonLocations()
    {   
        
        for(int i = 1; i <= 5; i++)
        {
            int index = (int) Math.floor(Math.random()*locations.size());
            
            switch(i)
            {
                case 1 -> {
                    jButton1.setLocation(locations.remove(index));
                }
                
                case 2 -> {
                    jButton2.setLocation(locations.remove(index));
                }
                
                case 3 -> {
                    jButton3.setLocation(locations.remove(index));
                }
                
                case 4 -> {
                    jButton4.setLocation(locations.remove(index));
                }
                
                case 5 -> {
                    jButton5.setLocation(locations.remove(index));
                    
                    System.out.println("------LOCATIONS------");
                    System.out.println(jButton1.getLocation());
                    System.out.println(jButton2.getLocation());
                    System.out.println(jButton3.getLocation());
                    System.out.println(jButton4.getLocation());
                    System.out.println(jButton5.getLocation());
                    System.out.println("---------------------");
                }
                    
            }
        }
        
        initializePossibleLocations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 400));
        setLayout(null);

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(64, 124, 75, 23);

        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(217, 124, 75, 23);

        jButton3.setText("jButton3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(359, 124, 75, 23);

        jButton4.setText("jButton4");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(146, 225, 75, 23);

        jButton5.setText("jButton5");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(302, 225, 75, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(red1);
//        System.out.println(jButton1.getLocation());
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(red);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setBackground(yellow1);
//        System.out.println(jButton2.getLocation());
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBackground(yellow);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        jButton3.setBackground(green1);
//        System.out.println(jButton3.getLocation());
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setBackground(green);
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        jButton4.setBackground(blue1);
//        System.out.println(jButton4.getLocation());
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jButton4.setBackground(blue);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        jButton5.setBackground(purple1);
//        System.out.println(jButton5.getLocation());
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setBackground(purple);
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        randomizeButtonLocations();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        randomizeButtonLocations();
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
        randomizeButtonLocations();
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // TODO add your handling code here:
        randomizeButtonLocations();
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        // TODO add your handling code here:
        randomizeButtonLocations();
    }//GEN-LAST:event_jButton5MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
