/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pointandclickswingproject;
import static com.mycompany.pointandclickswingproject.PointAndClickSwingProject.w;

/**
 *
 *
 */
public class GameOverScreen extends javax.swing.JPanel {

    /**
     * Creates new form GameOverScreen
     */
    public GameOverScreen() {
        initComponents();
    }
    
    private GameScreen gameMethods;
    
    /**
     * Creates new form GameOverScreen2
     * @param gameScreen1
     */    
    public GameOverScreen(GameScreen gameScreen1) {
        gameMethods = gameScreen1;
        initComponents();
    }
    
    private String getGameOverText() {
        if (gameMethods.getScore() == 0) {
            return "Game over!\nYour score is 0.";
        }
        else {
            return "Congratulations!\n You scored" + gameMethods.getScore() + "points.";
        }
           
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonBackToMenu = new javax.swing.JButton();
        labelScore = new javax.swing.JLabel();
        bgGameOverScreen = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonBackToMenu.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        buttonBackToMenu.setText("END");
        buttonBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackToMenuActionPerformed(evt);
            }
        });
        add(buttonBackToMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        labelScore.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        labelScore.setText(getGameOverText());
        add(labelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bgGameOverScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgGameOver.png"))); // NOI18N
        add(bgGameOverScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 270, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackToMenuActionPerformed
        // TODO add your handling code here:
        w.switchPanes("menu");
        gameMethods.resetHangman(100, 0, 0);
    }//GEN-LAST:event_buttonBackToMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgGameOverScreen;
    private javax.swing.JButton buttonBackToMenu;
    javax.swing.JLabel labelScore;
    // End of variables declaration//GEN-END:variables
}
