/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pointandclickswingproject;
import java.awt.event.*;
import javax.swing.Timer;

/**
 *
 * @author PC
 */
public class mainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public mainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        splashScreen1 = new com.mycompany.pointandclickswingproject.SplashScreen();
        menuScreen1 = new com.mycompany.pointandclickswingproject.MenuScreen();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(splashScreen1, "card3");
        mainPanel.add(menuScreen1, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ActionListener hideScreen = new ActionListener(){
        public void actionPerformed(ActionEvent evt) {
                //...Perform a task...
                splashScreen1.setVisible(false);
            }
        };
                
        Timer timer = new Timer(3000, hideScreen);
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ActionListener hideScreen = new ActionListener(){
            public void actionPerformed(ActionEvent evt) {
                //...Perform a task...
                splashScreen1.setVisible(false);
            }
        };
                
        Timer timer = new Timer(3000, hideScreen);
        timer.start();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private com.mycompany.pointandclickswingproject.MenuScreen menuScreen1;
    private com.mycompany.pointandclickswingproject.SplashScreen splashScreen1;
    // End of variables declaration//GEN-END:variables
}
